# Site settings
name: Mengti Sun
title: Mengti Sun | Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://chrissun99.github.io/
baseurl: ''
email: mengtisun@berkeley.edu
cover: https://chrissun99.github.io/img/og.png
logo: https://chrissun99.github.io/img/emojis/technologist.png
resume: https://chrissun99.github.io/resume.pdf
social:
  - title: email
    url: mailto:mengtisun@berkeley.edu
  - title: github
    url: https://github.com/ChrisSun99
  - title: linkedin
    url: https://www.linkedin.com/in/mengti-sun-4661b2140/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
